UPDATE [CDS.26]
SET [Assessor] = CASE WHEN [Assessor] like 'Gre%' or [Assessor] like '%Kerr%' THEN 'Greg Kerr' 
WHEN [Assessor] like '%Peter A%' THEN 'Peter Armstrong' 
WHEN [Assessor] like '%Ace%' THEN 'ACE Assessing Services'
WHEN [Assessor] like '%Alfonso%' THEN 'Alfonso Carbone'
WHEN [Assessor] like '%Awad%' THEN 'Awad Dabit'
WHEN [Assessor] like '%Crighton%' THEN 'Brad Crighton' 
WHEN [Assessor] like 'Bradley Hogan' THEN 'Bradley Hogan'
WHEN [Assessor] like ' Brett Montgomery' THEN 'Brett Montgomery' 
WHEN [Assessor] like '%Henniker%' THEN 'Bradley Henniker' 
WHEN [Assessor] like '%Wither%' THEN 'Brad Wither'
WHEN [Assessor] like '%Con' OR [Assessor] like '%Trassari%' THEN 'Con Trassari'
WHEN [Assessor] like '%David%' OR [Assessor] like '%Gibson'THEN 'David Gibson'
WHEN [Assessor] like '%FADY' THEN 'Fady Tadros'
WHEN [Assessor] like '%Gavin%' OR [Assessor] like '%Wood'THEN 'Gavin Wood'
WHEN [Assessor] like '%Graham%' THEN 'Graham Roughley' 
WHEN [Assessor] like '%john%g%' THEN 'John Gurd' 
WHEN [Assessor] like '%Peter J%' THEN 'Peter Jacklin' 
WHEN [Assessor] like '%Peter M' THEN 'Peter Montgomery' 
WHEN [Assessor] like '%Nathan Hoffman%' THEN 'Nathan Hoffman' 
WHEN [Assessor] like '%STEVE% O%' THEN 'Steven O''Sullivan' 
WHEN [Assessor] like '%john Nan%' THEN 'John Nanassy' 
WHEN [Assessor] like '%Daren %' THEN 'Daren Weidner' 
WHEN [Assessor] like '%Beasley' THEN 'Darryl Beasley' 
WHEN [Assessor] like '%Darryl%' THEN 'Darryl Beasley' 
WHEN [Assessor] like '%David Ba%' THEN 'David Barill' 
WHEN [Assessor] like '%Dom%' THEN 'Domenic gaglioti' 
WHEN [Assessor] like '%Ian%' THEN 'Ian McCausland' 
WHEN [Assessor] like '%Eni%' OR [Assessor] like '%Enni%' THEN 'Ennio Barbiero' 
WHEN [Assessor] like '%Gre%' THEN 'Greg Kerr' 
WHEN [Assessor] like '%martin b%' THEN 'Martin Bennett' 
WHEN [Assessor] like '%John L%' OR [Assessor] like '%McKee'THEN 'John L Mckee'
WHEN [Assessor] like '%steven%K%' THEN 'Steve Kouis'
WHEN [Assessor] like '%Reeve' THEN 'Peter Reeve'
WHEN [Assessor] like 'Renzo%' THEN 'Renzo De Castro'

ELSE [Assessor] END

UPDATE [CDS.26 Fleet Assessment Monthly]
SET [Assessed BY] = CASE WHEN [Assessed BY] like 'Gre%' or [Assessed BY] like '%Kerr%'THEN 'Greg Kerr' 
WHEN [Assessed BY] like '%Peter A%' THEN 'Peter Armstrong' 
WHEN [Assessed BY] like '%Ace%' THEN 'ACE Assessing Services' 
WHEN [Assessed BY] like '%Alfonso%' THEN 'Alfonso Carbone'
WHEN [Assessed BY] like '%Awad%' THEN 'Awad Dabit'
WHEN [Assessed BY] like '%Crighton%,' THEN 'Brad Crighton' 
WHEN [Assessed BY] like 'Bradley Hogan' THEN 'Bradley Hogan'
WHEN [Assessed BY] like ' Brett Montgomery' THEN 'Brett Montgomery' 
WHEN [Assessed BY] like '%Henniker%' THEN 'Bradley Henniker'
WHEN [Assessed BY] like '%Wither%' THEN 'Brad Wither'
WHEN [Assessed BY] like '%Con' OR [Assessed BY] like '%Trassari%' THEN 'Con Trassari'
WHEN [Assessed BY] like '%David%' OR [Assessed BY] like '%Gibson'THEN 'David Gibson'
WHEN [Assessed BY] like '%FADY' THEN 'Fady Tadros'
WHEN [Assessed BY] like '%Gavin%' OR [Assessed BY] like '%Wood'THEN 'Gavin Wood'
WHEN [Assessed BY] like '%Graham%' THEN 'Graham Roughley' 
WHEN [Assessed BY] like '%john%g%' THEN 'John Gurd' 
WHEN [Assessed BY] like '%Peter J%' THEN 'Peter Jacklin' 
WHEN [Assessed BY] like '%Peter M' THEN 'Peter Montgomery' 
WHEN [Assessed BY] like '%Nathan Hoffman%' THEN 'Nathan Hoffman' 
WHEN [Assessed BY] like '%STEVE% O%' THEN 'Steven O''Sullivan' 
WHEN [Assessed BY] like '%john Nan%' THEN 'John Nanassy' 
WHEN [Assessed BY] like '%Daren %' THEN 'Daren Weidner' 
WHEN [Assessed BY] like '%Beasley' THEN 'Darryl Beasley' 
WHEN [Assessed BY] like '%Darryl%' THEN 'Darryl Beasley' 
WHEN [Assessed BY] like '%David Ba%' THEN 'David Barill' 
WHEN [Assessed BY] like '%Dom%' THEN 'Domenic gaglioti' 
WHEN [Assessed BY] like '%Ian%' THEN 'Ian McCausland' 
WHEN [Assessed BY] like '%Eni%' OR [Assessed BY] like '%Enni%' THEN 'Ennio Barbiero' 
WHEN [Assessed BY] like '%Gre%' THEN 'Greg Kerr' 
WHEN [Assessed BY] like '%martin b%' THEN 'Martin Bennett' 
WHEN [Assessed BY] like '%steven%K%' THEN 'Steve Kouis'
WHEN [Assessed BY] like '%John L%' OR [Assessed BY] like '%McKee'THEN 'John L Mckee' 
WHEN [Assessed BY] like '%Reeve' THEN 'Peter Reeve'
WHEN [Assessed BY] like 'Renzo%' THEN 'Renzo De Castro'

ELSE [Assessed BY] END

UPDATE [CDS.26 Fleet Assessment Monthly]
SET [Incident State] = CASE WHEN  [Incident State] = 'coomNSW' or [Incident State] = '"'  THEN 'NSW'
WHEN [Incident State] = 'Q;D' THEN 'QLD'
WHEN [Incident State] = '6167' THEN 'WA' ELSE [Incident State] END

DELETE FROM [CDS.26 Fleet Assessment Monthly]
WHERE [Company Name] = 'Assessor Testing'