DROP table if exists [CDS.34 Union Staging]
CREATE TABLE [CDS.34 Union Staging] (
    [Active] nvarchar(255),
    [All Receipts] float,
    [Assessing Fee] float,
    [ASSESSMENT (+ Tax)] float,
    [Assessor] nvarchar(255),
    [Assessor State] nvarchar(255),
    [CLAIM STATUS] nvarchar(255),
    [CLIENT] nvarchar(255),
    [Client Cost inc tax] float,
    [Client Repairer] nvarchar(255),
    [COMPANY NAME] nvarchar(255),
    [CONSOLIDATOR] nvarchar(255),
    [Assessment Type] nvarchar(255),
    [Claim No] nvarchar(255),
    [Claimant] nvarchar(255),
    [Status] nvarchar(255),
    [CREATION DATE] datetime,
    [Date joined] datetime,
    [Date terminated] datetime,
    [ESTIMATE (+ Tax)] float,
    [Fleet] nvarchar(255),
    [Heavy Capability] nvarchar(255),
    [Heavy Vehicle] nvarchar(255),
    [Incident Time] nvarchar(255),
    [Insurance] nvarchar(255),
    [Key] nvarchar(510),
    [MARKET SEGMENT] nvarchar(255),
    [Motorbike] nvarchar(255),
    [Network] nvarchar(255),
    [Preferred Name] nvarchar(255),
    [Prestige] nvarchar(255),
    [Repairer Name] nvarchar(255),
    [REPAIRS INVOICED (+GST)] float,
    [Repairs Invoiced inc tax] numeric(14,2),
    [Standard] nvarchar(255),
    [TOTAL LOSS] nvarchar(255),
    [Vehicle Make] nvarchar(255),
    [Vehicle Model] nvarchar(255),
    [Vehicle Rego] nvarchar(255),
    [Vehicle State] nvarchar(255),
    [Warriewood] nvarchar(255),
    [Incident Code] nvarchar(255),
    [Assessment Completed Date] datetime,
    [REPORT DATE] datetime
)