SELECT 
[1 IG_Grp_QueuesByExecutive],
[2 IG_Grp_QueuesByPortfolio],
[3 IG_Grp_QueuesByTeam],
[4 IG_Grp_QueueNameForReporting],
[ID],
[QueueAnswerByGroup1],
[QueueAnswerByGroup2],
[QueueAnswerByGroup3],
[QueueAnswerByGroup4],
a.[Queue Name],
[Queue Reporting],
[Queue Dialable],
[Day Of Week Name],
[Media Server Name],
[Interval Start Time],
[Midnight Start Date],
[Day Of Week ID],
[Time Interval ID],
a.[Queue ID],
[Queue Answered],
[Queue Abandoned],
[Queue Interflowed],
[Queue Unavailable],
[Queue Requeued],
[Queue Total Talk Time],
[Queue Time To Abandon Total],
[Queue Time To Interflow Total],
[Queue Time To Answer Total],
[Queue Service Count],
[Queue Offered],
[Queue Short Abandoned],
[Queue Short Talk],
[Queue Maximum Calls Waiting],
[Queue Agents Available Minimum],
[Queue Agents Available Maximum],
[Queue Occupancy],
[Queue Make Busy Duration],
[Queue Make Busy Count],
[Queue Answered ACD Not By Agent],
[Queue Answered ACD By Agent],
[Queue Answered ACD Agent Duration],
[Queue ACD Hold By Agent],
[Queue Transfer To Agent Duration],
[Queue Transfer To Agent Hold Duration],
[Queue Transfer Not To Agent Count],
[Queue Number Of Extension Answered DID Calls],
[Queue Total Duration Extension Answered DID Calls],
[Queue Number Of Extension External Outbound Calls],
[Queue Total Duration Extension External Outbound Calls],
[Queue Wrap Up By Agent Duration],
[Queue Internal ACD Count],
[Queue Internal ACD Duration],
[Queue External ACD Count],
[Queue External ACD Duration],
[Queue ACD Hold By Agent Duration],
[Queue Transfer To Agent Count],
[Queue Transfer To Agent Hold Count],
[Queue Wrap Up By Agent Count],
[Queue Maximum Longest Waiting Calls],
1 as [Number of Records]

from [CDS.30]  a
left join
[CDS.30 Hierarchy] b
on a.[Queue ID] = b.[Queue ID]


