Select top(1)

[DayOfWeekID] as [Day Of Week ID],
[DayOfWeekName] as [Day Of Week Name],
[ID] as [ID],
[IntervalStartTime] as [Interval Start Time],
[MediaServerName] as [Media Server Name],
[MidnightStartDate] as [Midnight Start Date],
[QueueAbandoned] as [Queue Abandoned],
[QueueACDHoldByAgent] as [Queue ACD Hold By Agent],
[QueueACDHoldByAgentDuration] as [Queue ACD Hold By Agent Duration],
[QueueAgentsAvailableMaximum] as [Queue Agents Available Maximum],
[QueueAgentsAvailableMinimum] as [Queue Agents Available Minimum],
[QueueAnswered] as [Queue Answered],
[QueueAnsweredACDAgentDuration] as [Queue Answered ACD Agent Duration],
[QueueAnsweredACDByAgent] as [Queue Answered ACD By Agent],
[QueueAnsweredACDNotByAgent] as [Queue Answered ACD Not By Agent],
[QueueDialable] as [Queue Dialable],
[QueueExternalACDCount] as [Queue External ACD Count],
[QueueExternalACDDuration] as [Queue External ACD Duration],
[QueueID] as [Queue ID],
[QueueInterflowed] as [Queue Interflowed],
[QueueInternalACDCount] as [Queue Internal ACD Count],
[QueueInternalACDDuration] as [Queue Internal ACD Duration],
[QueueMakeBusyCount] as [Queue Make Busy Count],
[QueueMakeBusyDuration] as [Queue Make Busy Duration],
[QueueMaximumCallsWaiting] as [Queue Maximum Calls Waiting],
[QueueMaximumLongestWaitingCalls] as [Queue Maximum Longest Waiting Calls],
[QueueName] as [Queue Name],
[QueueNumberOfExtensionAnsweredDIDCalls] as [Queue Number Of Extension Answered DID Calls],
[QueueNumberOfExtensionExternalOutboundCalls] as [Queue Number Of Extension External Outbound Calls],
[QueueOccupancy] as [Queue Occupancy],
[QueueOffered] as [Queue Offered],
[QueueReporting] as [Queue Reporting],
[QueueRequeued] as [Queue Requeued],
[QueueServiceCount] as [Queue Service Count],
[QueueShortAbandoned] as [Queue Short Abandoned],
[QueueShortTalk] as [Queue Short Talk],
[QueueTimeToAbandonTotal] as [Queue Time To Abandon Total],
[QueueTimeToAnswerTotal] as [Queue Time To Answer Total],
[QueueTimeToInterflowTotal] as [Queue Time To Interflow Total],
[QueueTotalDurationExtensionAnsweredDIDCalls] as [Queue Total Duration Extension Answered DID Calls],
[QueueTotalDurationExtensionExternalOutboundCalls] as [Queue Total Duration Extension External Outbound Calls],
[QueueTotalTalkTime] as [Queue Total Talk Time],
[QueueTransferNotToAgentCount] as [Queue Transfer Not To Agent Count],
[QueueTransferToAgentCount] as [Queue Transfer To Agent Count],
[QueueTransferToAgentDuration] as [Queue Transfer To Agent Duration],
[QueueTransferToAgentHoldCount] as [Queue Transfer To Agent Hold Count],
[QueueTransferToAgentHoldDuration] as [Queue Transfer To Agent Hold Duration],
[QueueUnavailable] as [Queue Unavailable],
[QueueWrapUpByAgentCount] as [Queue Wrap Up By Agent Count],
[QueueWrapUpByAgentDuration] as [Queue Wrap Up By Agent Duration],
[TimeIntervalID] as [Time Interval ID],
[QueueAnswerByGroup1] as [QueueAnswerByGroup1],
[QueueAnswerByGroup2] as [QueueAnswerByGroup2],
[QueueAnswerByGroup3] as [QueueAnswerByGroup3],
[QueueAnswerByGroup4] as [QueueAnswerByGroup4],
1 as [Number of Records]


from 

[CCMData].[dbo].[QueuePerformanceByPeriodStats]

where [MidnightStartDate] >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE())-1, 0) 
and [MidnightStartDate] < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0)