CREATE TABLE [Mitel] (
    [Agent Event ACD Count] float,
    [Agent Event ACD Duration] float,
    [Agent Event ACD Hold Count] float,
    [Agent Event ACD Hold Duration] float,
    [Agent Event ACD Short] float,
    [Agent Event DND Count] float,
    [Agent Event DND Duration] float,
    [Agent Event Login Time] datetime,
    [Agent Event Logout Time] datetime,
    [Agent Event Make Busy Count] float,
    [Agent Event Make Busy Duration] float,
    [Agent Event Non ACD Count] float,
    [Agent Event Non ACD Duration] float,
    [Agent Event Non ACD Hold Count] float,
    [Agent Event Non ACD Hold Duration] float,
    [Agent Event Outbound Count] float,
    [Agent Event Outbound Duration] float,
    [Agent Event Outbound Hold Count] float,
    [Agent Event Outbound Hold Duration] float,
    [Agent Event Ringing Count] float,
    [Agent Event Ringing Duration] float,
    [Agent Event Shift Duration] float,
    [Agent Event Wrap Up Duration] float,
    [Agent First Name] nvarchar(255),
    [Agent ID] nvarchar(255),
    [Agent Last Name] nvarchar(255),
    [Agent Media Server Name] nvarchar(255),
    [Agent Reporting] float,
    [Day Of Week ID] float,
    [Day Of Week Name] nvarchar(255),
    [Employee First Name] nvarchar(255),
    [Employee ID] nvarchar(255),
    [Employee Last Name] nvarchar(255),
    [Employee Reporting] float,
    [Interval Start Time] nvarchar(255),
    [Midnight Start Date] datetime,
    [Number of Records] float,
    [Position] float,
    [Time Interval ID] float
)