CREATE TABLE [CDS.30] (
    [Day Of Week ID] float,
    [Day Of Week Name] nvarchar(255),
    [ID] nvarchar(255),
    [Interval Start Time] time,
    [Media Server Name] nvarchar(255),
    [Midnight Start Date] datetime,
    [Number of Records] float,
    [Queue ACD Hold By Agent Duration] float,
    [Queue ACD Hold By Agent] float,
    [Queue Abandoned] float,
    [Queue Agents Available Maximum] float,
    [Queue Agents Available Minimum] float,
    [QueueAnswerByGroup1] float,
    [QueueAnswerByGroup2] float,
    [QueueAnswerByGroup3] float,
    [QueueAnswerByGroup4] float,
    [Queue Answered ACD Agent Duration] float,
    [Queue Answered ACD By Agent] float,
    [Queue Answered ACD Not By Agent] float,
    [Queue Answered] float,
    [Queue Dialable] nvarchar(255),
    [Queue External ACD Count] float,
    [Queue External ACD Duration] float,
    [Queue ID] nvarchar(255),
    [Queue Interflowed] float,
    [Queue Internal ACD Count] float,
    [Queue Internal ACD Duration] float,
    [Queue Make Busy Count] float,
    [Queue Make Busy Duration] float,
    [Queue Maximum Calls Waiting] float,
    [Queue Maximum Longest Waiting Calls] float,
    [Queue Name] nvarchar(255),
    [Queue Number Of Extension Answered DID Calls] float,
    [Queue Number Of Extension External Outbound Calls] float,
    [Queue Occupancy] float,
    [Queue Offered] float,
    [Queue Reporting] nvarchar(255),
    [Queue Requeued] float,
    [Queue Service Count] float,
    [Queue Short Abandoned] float,
    [Queue Short Talk] float,
    [Queue Time To Abandon Total] float,
    [Queue Time To Answer Total] float,
    [Queue Time To Interflow Total] float,
    [Queue Total Duration Extension Answered DID Calls] float,
    [Queue Total Duration Extension External Outbound Calls] float,
    [Queue Total Talk Time] float,
    [Queue Transfer Not To Agent Count] float,
    [Queue Transfer To Agent Count] float,
    [Queue Transfer To Agent Duration] float,
    [Queue Transfer To Agent Hold Count] float,
    [Queue Transfer To Agent Hold Duration] float,
    [Queue Unavailable] float,
    [Queue Wrap Up By Agent Count] float,
    [Queue Wrap Up By Agent Duration] float,
    [Time Interval ID] float
)